import type { TaskDeps, TaskResult } from '../scheduler.js'
import { findBubblesByType, updateBubble, createBubble } from '../../bubble/model.js'
import { getDatabase } from '../../storage/database.js'
import { logger } from '../../shared/logger.js'
import type { Bubble, BubbleType, UserContext } from '../../shared/types.js'

/**
 * Self-Dialogue Engine — Bubble answers its own questions.
 *
 * Finds unanswered question bubbles and uses Brain.think() to answer them,
 * creating natural memory flow. When no questions exist, generates new ones
 * from recent memories. This solves the cold-start problem: even without
 * user interaction, Bubble keeps its learning loop alive.
 *
 * Registered as enabled, runs every 6 hours.
 */

const DAY_MS = 24 * 60 * 60 * 1000

const QUESTION_GEN_PROMPT = `你是一个以追问为核心的思维引擎。从以下记忆中发现 1 个值得深入探讨的问题。

要求：
1. 问题必须具体、可追踪，不是空泛的哲学感叹
2. 优先关注：数据之间的矛盾、沉默的变化、被忽视的关联
3. 问题应该能引发新的信息搜索或思考转变
4. 输出严格 JSON 格式：{"title":"问题标题(15字以内)","content":"问题描述(50-150字，包含追问逻辑)"}`

export async function executeSelfDialogue(
  params: Record<string, unknown>,
  deps: TaskDeps,
): Promise<TaskResult> {
  const maxQuestions = Number(params.maxQuestions) || 3
  const chatId = deps.feishu?.getAdminChatId() || String(params.chatId || process.env.FEISHU_ADMIN_CHAT_ID || '')

  // ── Find unanswered question bubbles across all spaces ─────────────
  const db = getDatabase()
  const spaceRows = db.prepare(
    'SELECT DISTINCT space_id FROM bubbles WHERE space_id IS NOT NULL',
  ).all() as Array<{ space_id: string }>
  const spaceIds = spaceRows.map(r => r.space_id)

  const now = Date.now()
  const allQuestions: Bubble[] = []

  // Collect questions from each space
  for (const sid of spaceIds) {
    try {
      const questions = findBubblesByType('question', 50, [sid])
      allQuestions.push(...questions)
    } catch (err) {
      logger.debug(`SelfDialogue: failed to query questions in space ${sid}: ${err instanceof Error ? err.message : String(err)}`)
    }
  }

  // Also check unscoped questions
  try {
    const unscopedQuestions = findBubblesByType('question', 50)
    for (const q of unscopedQuestions) {
      if (!q.spaceId && !allQuestions.some(aq => aq.id === q.id)) {
        allQuestions.push(q)
      }
    }
  } catch (err) {
    logger.debug(`SelfDialogue: failed to query unscoped questions: ${err instanceof Error ? err.message : String(err)}`)
  }

  // Filter: unanswered + anti-loop guard
  const unanswered = allQuestions
    .filter(b => {
      const meta = b.metadata as Record<string, unknown> | undefined
      if (meta?.answered === true) return false
      // Anti-loop: skip questions generated by self-dialogue within 24h
      if (b.source === 'self-dialogue' && b.createdAt > now - DAY_MS) return false
      return true
    })
    .sort((a, b) => a.createdAt - b.createdAt) // oldest first
    .slice(0, maxQuestions)

  const answeredIds: string[] = []
  const answers: Array<{ title: string; response: string }> = []

  // ── Answer each question ───────────────────────────────────────────
  for (const question of unanswered) {
    try {
      const ctx: UserContext = {
        userId: 'bubble-self',
        spaceIds: question.spaceId ? [question.spaceId] : [],
        activeSpaceId: question.spaceId ?? '',
      }

      logger.info(`SelfDialogue: thinking about "${question.title}"`)
      const result = await deps.brain.think(question.content, ctx)

      // Mark as answered
      const existingMeta = (question.metadata ?? {}) as Record<string, unknown>
      updateBubble(question.id, {
        metadata: {
          ...existingMeta,
          answered: true,
          answeredAt: Date.now(),
          answeredBy: 'self-dialogue',
          answer: result.response.slice(0, 500),
        },
      })

      answeredIds.push(question.id)
      answers.push({ title: question.title, response: result.response.slice(0, 200) })
      logger.info(`SelfDialogue: answered "${question.title}"`)
    } catch (err) {
      logger.error(`SelfDialogue: failed to answer "${question.title}": ${err instanceof Error ? err.message : String(err)}`)
    }
  }

  // ── Generate new question if none to answer ────────────────────────
  let generatedQuestionId: string | undefined

  if (unanswered.length === 0) {
    try {
      generatedQuestionId = await generateNewQuestion(deps, spaceIds)
    } catch (err) {
      logger.error(`SelfDialogue: question generation failed: ${err instanceof Error ? err.message : String(err)}`)
    }
  }

  // ── Optional Feishu notification ───────────────────────────────────
  if (deps.feishu && chatId && answers.length > 0) {
    try {
      const summary = answers
        .map((a, i) => `${i + 1}. ${a.title}\n   ${a.response}`)
        .join('\n\n')
      await deps.feishu.pushMessage(
        chatId,
        `自对话引擎回答了 ${answers.length} 个问题：\n\n${summary}`,
      )
    } catch (err) {
      logger.error(`SelfDialogue: Feishu push failed: ${err instanceof Error ? err.message : String(err)}`)
    }
  }

  // ── Return result ──────────────────────────────────────────────────
  const parts: string[] = []
  if (answers.length > 0) parts.push(`回答了 ${answers.length} 个问题`)
  if (generatedQuestionId) parts.push('生成了 1 个新问题')
  if (parts.length === 0) parts.push('无待回答问题，记忆不足，未生成新问题')

  const message = `自对话: ${parts.join(', ')}`
  logger.info(`SelfDialogue: ${message}`)

  const bubbleIds = [...answeredIds]
  if (generatedQuestionId) bubbleIds.push(generatedQuestionId)

  return { success: true, message, bubbleIds }
}

// ── Question generation from recent memories ─────────────────────────

async function generateNewQuestion(
  deps: TaskDeps,
  spaceIds: string[],
): Promise<string | undefined> {
  const db = getDatabase()
  const since = Date.now() - 7 * DAY_MS

  const recentRows = db.prepare(`
    SELECT id, type, title, content, space_id
    FROM bubbles
    WHERE type IN ('memory', 'synthesis', 'observation')
      AND created_at > ?
    ORDER BY created_at DESC LIMIT 20
  `).all(since) as Array<{ id: string; type: string; title: string; content: string; space_id: string | null }>

  if (recentRows.length < 3) {
    logger.debug('SelfDialogue: insufficient recent memories for question generation')
    return undefined
  }

  const summary = recentRows
    .map(r => `[${r.type}] ${r.title}: ${r.content.slice(0, 120)}`)
    .join('\n')

  const messages = [
    { role: 'system' as const, content: QUESTION_GEN_PROMPT },
    { role: 'user' as const, content: `以下是近 7 天的 ${recentRows.length} 条记忆：\n\n${summary}` },
  ]

  const response = await deps.llm.chat(messages)
  const text = response.content.trim()

  const jsonMatch = text.match(/\{[\s\S]*\}/)
  if (!jsonMatch) {
    logger.debug('SelfDialogue: no JSON in LLM response for question generation')
    return undefined
  }

  const parsed = JSON.parse(jsonMatch[0]) as { title?: string; content?: string }
  if (!parsed.title || !parsed.content) {
    logger.debug('SelfDialogue: invalid question JSON from LLM')
    return undefined
  }

  const spaceId = recentRows[0].space_id ?? undefined
  const bubble = createBubble({
    type: 'question' as BubbleType,
    title: parsed.title,
    content: parsed.content,
    tags: ['question', 'self-dialogue', 'auto-generated'],
    source: 'self-dialogue',
    confidence: 0.7,
    decayRate: 0.15,
    spaceId,
  })

  logger.info(`SelfDialogue: generated question "${bubble.title}"`)
  return bubble.id
}
